services:
  backend:
    build: ./backend
    ports: [ "8000:8000" ]
    volumes:
      # Persist evaluation results between container restarts
      - ./backend/evaluation/results:/app/evaluation/results
    environment:
      - CATALOG_PATH=/app/data/catalog.csv
      - ALLOWED_ORIGINS=http://localhost:3000
  frontend:
    build: ./frontend
    ports: [ "3000:3000" ]
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8000
    depends_on: [ backend ]
